version: "3"

services:
  client:
    build: ./client/
    container_name: client
    restart: always
    # ports:
    #   - 3000:3000
    volumes:
      - ./client/:/app

  nginx:
    build: ./nginx/
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./client/.nuxt/dist:/data/Test/client/dist
    depends_on:
      - client